export interface MainState {
    imgLoadStatus: boolean;
    innerWidth: number | null;
    coverType: number;
    sBGCount: string | null;
    autoBGSwitchInterval : number;
    seasonalEffects: boolean;
    msgNameShow: boolean;
    siteStartShow: boolean;
    musicClick: boolean;
    musicBoxOpenState: boolean;
    musicIsOk: boolean;
    musicVolume: number;
    musicOpenState: boolean;
    backgroundShow: boolean;
    boxOpenState: boolean;
    mobileOpenState: boolean;
    mobileFuncState: boolean;
    setOpenState: boolean;
    setV: boolean;
    playerState: boolean;
    playerCanplay: boolean;
    playerTitle: string | null;
    playerArtist: string | null;
    playerAlbum: string | null;
    playerLrc: [boolean, string, string, string, string, string, string][] | [boolean, string, string, string, string, string][] | [boolean, string, string, string, string][] | [boolean, string][];
    playerLrcShow: boolean;
    footerBlur: boolean;
    footerProgressBar: boolean;
    playerAutoplay: boolean;
    playerLoop: "all" | "one" | "none";
    playerOrder: "list" | "random";
    webSpeech: boolean;
    playerSpeechName: boolean;
    playerTrLrc: boolean;
    playerDWRCShow: boolean;
    playerDWRCShowPro: boolean;
    playerDWRCATDB: boolean;
    playerDWRCATDBF: boolean;
    playerDWRCPilfer: boolean;
    playerRMMetadata: boolean;
    playerCurrentTime: number | null;
    playerDuration: number | null;
    dwrcIndex: number | null;
    dwrcTemp: any[];
    dwrcEnable: boolean;
    dwrcLoading: boolean;
    lyricSeekVersion: number;
    forceShowBarIcon: boolean;
    showFirefly: boolean;
    showSnowfall: boolean;
    showLantern: boolean;
    showProgressIcon: boolean;
    showProgressIconState: number;
    theme: "system" | "time" | "bg" | "light" | "dark";
    language: "zh-CN" | "en";
};